/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ProtectedWorkspaceSettingsRouteImport } from './routes/_protected/workspace-settings'
import { Route as ProtectedTransactionsRouteImport } from './routes/_protected/transactions'
import { Route as ProtectedRecurringRouteImport } from './routes/_protected/recurring'
import { Route as ProtectedPreferencesRouteImport } from './routes/_protected/preferences'
import { Route as ProtectedIncomeRouteImport } from './routes/_protected/income'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedBudgetsRouteImport } from './routes/_protected/budgets'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiHelloRouteImport } from './routes/_api/hello'

const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedWorkspaceSettingsRoute =
  ProtectedWorkspaceSettingsRouteImport.update({
    id: '/workspace-settings',
    path: '/workspace-settings',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTransactionsRoute = ProtectedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRecurringRoute = ProtectedRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPreferencesRoute = ProtectedPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIncomeRoute = ProtectedIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBudgetsRoute = ProtectedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/_api/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/oauth-callback': typeof OauthCallbackRoute
  '/hello': typeof ApiHelloRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/budgets': typeof ProtectedBudgetsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/income': typeof ProtectedIncomeRoute
  '/preferences': typeof ProtectedPreferencesRoute
  '/recurring': typeof ProtectedRecurringRoute
  '/transactions': typeof ProtectedTransactionsRoute
  '/workspace-settings': typeof ProtectedWorkspaceSettingsRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesByTo {
  '/oauth-callback': typeof OauthCallbackRoute
  '/hello': typeof ApiHelloRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/budgets': typeof ProtectedBudgetsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/income': typeof ProtectedIncomeRoute
  '/preferences': typeof ProtectedPreferencesRoute
  '/recurring': typeof ProtectedRecurringRoute
  '/transactions': typeof ProtectedTransactionsRoute
  '/workspace-settings': typeof ProtectedWorkspaceSettingsRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/oauth-callback': typeof OauthCallbackRoute
  '/_api/hello': typeof ApiHelloRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_protected/budgets': typeof ProtectedBudgetsRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/income': typeof ProtectedIncomeRoute
  '/_protected/preferences': typeof ProtectedPreferencesRoute
  '/_protected/recurring': typeof ProtectedRecurringRoute
  '/_protected/transactions': typeof ProtectedTransactionsRoute
  '/_protected/workspace-settings': typeof ProtectedWorkspaceSettingsRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/oauth-callback'
    | '/hello'
    | '/sign-in'
    | '/sign-out'
    | '/budgets'
    | '/dashboard'
    | '/income'
    | '/preferences'
    | '/recurring'
    | '/transactions'
    | '/workspace-settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/oauth-callback'
    | '/hello'
    | '/sign-in'
    | '/sign-out'
    | '/budgets'
    | '/dashboard'
    | '/income'
    | '/preferences'
    | '/recurring'
    | '/transactions'
    | '/workspace-settings'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/oauth-callback'
    | '/_api/hello'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_protected/budgets'
    | '/_protected/dashboard'
    | '/_protected/income'
    | '/_protected/preferences'
    | '/_protected/recurring'
    | '/_protected/transactions'
    | '/_protected/workspace-settings'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  OauthCallbackRoute: typeof OauthCallbackRoute
  ApiHelloRoute: typeof ApiHelloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/workspace-settings': {
      id: '/_protected/workspace-settings'
      path: '/workspace-settings'
      fullPath: '/workspace-settings'
      preLoaderRoute: typeof ProtectedWorkspaceSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/transactions': {
      id: '/_protected/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ProtectedTransactionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/recurring': {
      id: '/_protected/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof ProtectedRecurringRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/preferences': {
      id: '/_protected/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof ProtectedPreferencesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/income': {
      id: '/_protected/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof ProtectedIncomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/budgets': {
      id: '/_protected/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof ProtectedBudgetsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_api/hello': {
      id: '/_api/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedBudgetsRoute: typeof ProtectedBudgetsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedIncomeRoute: typeof ProtectedIncomeRoute
  ProtectedPreferencesRoute: typeof ProtectedPreferencesRoute
  ProtectedRecurringRoute: typeof ProtectedRecurringRoute
  ProtectedTransactionsRoute: typeof ProtectedTransactionsRoute
  ProtectedWorkspaceSettingsRoute: typeof ProtectedWorkspaceSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBudgetsRoute: ProtectedBudgetsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedIncomeRoute: ProtectedIncomeRoute,
  ProtectedPreferencesRoute: ProtectedPreferencesRoute,
  ProtectedRecurringRoute: ProtectedRecurringRoute,
  ProtectedTransactionsRoute: ProtectedTransactionsRoute,
  ProtectedWorkspaceSettingsRoute: ProtectedWorkspaceSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  OauthCallbackRoute: OauthCallbackRoute,
  ApiHelloRoute: ApiHelloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
